version: "3.3"
services:
  api:
    container_name: instagram-clone-api
    build:
      context: ./api
      dockerfile: Dockerfile-prod
    volumes:
      - node_modules:/app/node_modules
    env_file:
      - .env.prod
    ports:
      - 80:4001
volumes:
  node_modules:
