version: "3.4"
services:
  api:
    container_name: instagram-clone-api
    build:
      context: ./api
      dockerfile: Dockerfile-dev
    volumes:
      - ./api:/app
    ports:
      - 80:4001
    env_file:
      - .env
    networks:
      - instagram-clone-network
