"use strict";

module.exports = {
  up: async (queryInterface) => {
    await queryInterface.bulkInsert(
      "Users",
      [
        {
          first_name: "Jinny",
          middle_name: "Marsha",
          last_name: "Runacres",
          phone_number: "+886 0970699044",
          email: "dwindeatt0@theatlantic.com",
          dob: "1986/02/08",
          gender: "FEMALE",
          pic: "http://dummyimage.com/174x176.png/5fa2dd/ffffff",
          status: "ONLINE",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Joey",
          middle_name: "Welbie",
          last_name: "Fish",
          phone_number: "+886 0970699044",
          email: "amalenoir1@oaic.gov.au",
          dob: "2020/01/28",
          gender: "MALE",
          pic: "http://dummyimage.com/103x213.png/5fa2dd/ffffff",
          member_type: "BASIC",
          status: "ACTIVE",
          free_trial: "UNUSED",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Floyd",
          middle_name: "Clary",
          last_name: "Giannazzi",
          phone_number: "+886 0970699044",
          email: "ryukhtin2@buzzfeed.com",
          dob: "1979/03/29",
          gender: "MALE",
          pic: "http://dummyimage.com/129x151.png/ff4444/ffffff",
          member_type: "BASIC",
          status: "ACTIVE",
          free_trial: "UNUSED",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Glenna",
          middle_name: "Scotti",
          last_name: "Snelling",
          phone_number: "+886 0970699044",
          email: "ylabuschagne3@tmall.com",
          dob: "2012/10/12",
          gender: "FEMALE",
          pic: "http://dummyimage.com/180x126.png/cc0000/ffffff",
          member_type: "N/A",
          status: "DEACTIVATED",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Leanora",
          middle_name: "Peder",
          last_name: "MacMenemy",
          phone_number: "+886 0970699044",
          email: "sconyer4@yelp.com",
          dob: "1994/12/09",
          gender: "MALE",
          pic: "http://dummyimage.com/128x151.png/5fa2dd/ffffff",
          member_type: "N/A",
          status: "ACTIVE",
          free_trial: "UNUSED",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Hallie",
          middle_name: "Chandal",
          last_name: "Gruszka",
          phone_number: "+886 0970699044",
          email: "tmarcone5@ning.com",
          dob: "1998/01/22",
          gender: "Male",
          pic: "http://dummyimage.com/165x115.png/5fa2dd/ffffff",
          member_type: "N/A",
          status: "ACTIVE",
          free_trial: "UNUSED",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Gunilla",
          middle_name: "Margy",
          last_name: "Peverell",
          phone_number: "+886 0970699044",
          email: "mhepher6@meetup.com",
          dob: "1977/01/18",
          gender: "MALE",
          pic: "http://dummyimage.com/151x157.png/ff4444/ffffff",
          member_type: "BASIC",
          status: "ACTIVE",
          free_trial: "UNUSED",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Delainey",
          middle_name: "Alyse",
          last_name: "MacDuff",
          phone_number: "+886 0970699044",
          email: "nbonwick7@icio.us",
          dob: "1977/04/11",
          gender: "FEMALE",
          pic: "http://dummyimage.com/194x101.png/ff4444/ffffff",
          member_type: "N/A",
          status: "DEACTIVATED",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Geri",
          middle_name: "Wyndham",
          last_name: "MacVay",
          phone_number: "+886 0970699044",
          email: "csaltsberger8@webeden.co.uk",
          dob: "1970/06/13",
          gender: "Male",
          pic: "http://dummyimage.com/104x189.png/5fa2dd/ffffff",
          member_type: "N/A",
          status: "ACTIVE",
          free_trial: "UNUSED",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Winston",
          middle_name: "Lawrence",
          last_name: "Endacott",
          phone_number: "+886 0970699044",
          email: "jlashley9@free.fr",
          dob: "1987/05/31",
          gender: "FEMALE",
          pic: "http://dummyimage.com/139x100.png/dddddd/000000",
          member_type: "PRO",
          status: "ACTIVE",
          free_trial: "UNUSED",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Jeramie",
          middle_name: "Anita",
          last_name: "Manneville",
          phone_number: "+886 0970699044",
          email: "tpesslera@utexas.edu",
          dob: "1974/07/09",
          gender: "FEMALE",
          pic: "http://dummyimage.com/139x153.png/dddddd/000000",
          member_type: "PRO",
          status: "ACTIVE",
          free_trial: "UNUSED",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Rockwell",
          middle_name: "Lotte",
          last_name: "Gilffilland",
          phone_number: "+886 0970699044",
          email: "nslayfordb@t-online.de",
          dob: "2017/09/01",
          gender: "FEMALE",
          pic: "http://dummyimage.com/119x178.png/5fa2dd/ffffff",
          member_type: "BASIC",
          status: "DEACTIVATED",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Rosemarie",
          middle_name: "Derry",
          last_name: "Crickmoor",
          phone_number: "+886 0970699044",
          email: "btorrc@skyrock.com",
          dob: "1987/01/04",
          gender: "FEMALE",
          pic: "http://dummyimage.com/159x176.png/dddddd/000000",
          member_type: "BASIC",
          status: "ACTIVE",
          free_trial: "UNUSED",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Christopher",
          middle_name: "Sinclare",
          last_name: "Lydiatt",
          phone_number: "+886 0970699044",
          email: "adunicand@360.cn",
          dob: "1980/04/09",
          gender: "Female",
          pic: "http://dummyimage.com/143x213.png/5fa2dd/ffffff",
          member_type: "PRO",
          status: "ACTIVE",
          free_trial: "UNUSED",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Sari",
          middle_name: "Hagan",
          last_name: "Jovis",
          phone_number: "+886 0970699044",
          email: "rcurralle@mediafire.com",
          dob: "2002/07/20",
          gender: "MALE",
          pic: "http://dummyimage.com/228x202.png/5fa2dd/ffffff",
          member_type: "BASIC",
          status: "ACTIVE",
          free_trial: "UNUSED",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Janenna",
          middle_name: "Richmond",
          last_name: "Shipman",
          phone_number: "+886 0970699044",
          email: "hcoveneyf@reuters.com",
          dob: "1976/08/09",
          gender: "MALE",
          pic: "http://dummyimage.com/176x244.png/ff4444/ffffff",
          member_type: "PRO",
          status: "ACTIVE",
          free_trial: "UNUSED",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Des",
          middle_name: "Maryann",
          last_name: "Vaskov",
          phone_number: "+886 0970699044",
          email: "lcaesmang@google.de",
          dob: "1997/01/13",
          gender: "FEMALE",
          pic: "http://dummyimage.com/165x234.png/ff4444/ffffff",
          member_type: "BASIC",
          status: "ACTIVE",
          free_trial: "UNUSED",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Dolf",
          middle_name: "Dalt",
          last_name: "Greeve",
          phone_number: "+886 0970699044",
          email: "dgoreh@uol.com.br",
          dob: "2012/08/18",
          gender: "MALE",
          pic: "http://dummyimage.com/222x113.png/5fa2dd/ffffff",
          member_type: "PRO",
          status: "DEACTIVATED",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Gawen",
          middle_name: "Nelle",
          last_name: "Hercules",
          phone_number: "+886 0970699044",
          email: "tbyhami@gravatar.com",
          dob: "2009/12/31",
          gender: "FEMALE",
          pic: "http://dummyimage.com/179x143.png/dddddd/000000",
          member_type: "PRO",
          status: "ACTIVE",
          free_trial: "UNUSED",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Lottie",
          middle_name: "Vance",
          last_name: "Farahar",
          phone_number: "+886 0970699044",
          email: "wtittletrossj@1und1.de",
          dob: "2012/01/02",
          gender: "FEMALE",
          pic: "http://dummyimage.com/172x203.png/5fa2dd/ffffff",
          member_type: "BASIC",
          status: "ACTIVE",
          free_trial: "UNUSED",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  down: async (queryInterface) => {
    await queryInterface.bulkDelete("Users", null, {});
  },
};
